# Copy to supabase/migrations/001_initial.sql in a Supabase project
create type public.app_role as enum ('student','teacher','admin','parent');
create table public.profiles (id uuid primary key references auth.users on delete cascade, full_name text not null, email text, phone text, preferred_language text default 'en', role public.app_role default 'student', school_id uuid, grade_id bigint, created_at timestamptz default now());
create table public.schools (id bigint generated always as identity primary key, name text not null, city text, created_at timestamptz default now());
create table public.grades (id bigint generated always as identity primary key, number int unique not null check(number between 5 and 11));
create table public.subjects (id bigint generated always as identity primary key, name text not null, code text unique, active boolean default true);
create table public.courses (id bigint generated always as identity primary key, subject_id bigint references subjects, grade_id bigint references grades, title text not null, description text);
create table public.topics (id bigint generated always as identity primary key, course_id bigint references courses on delete cascade, title text not null);
create table public.lessons (id bigint generated always as identity primary key, topic_id bigint references topics on delete cascade, title text not null, body text, position int default 0);
create table public.resources (id bigint generated always as identity primary key, lesson_id bigint references lessons on delete cascade, title text not null, kind text, storage_path text, external_url text, downloadable boolean default true);
create table public.live_classes (id bigint generated always as identity primary key, subject_id bigint references subjects, grade_id bigint references grades, teacher_id uuid references profiles, starts_at timestamptz not null, duration_minutes int check(duration_minutes between 1 and 60), meet_url text, recording_url text);
create table public.student_progress (id bigint generated always as identity primary key, student_id uuid references profiles on delete cascade, lesson_id bigint references lessons on delete cascade, percent int default 0 check(percent between 0 and 100), completed_at timestamptz, unique(student_id,lesson_id));
create table public.mosuoe_conversations (id uuid primary key default gen_random_uuid(), student_id uuid references profiles on delete cascade, grade_id bigint references grades, subject_id bigint references subjects, topic_id bigint references topics, created_at timestamptz default now());
create table public.mosuoe_messages (id bigint generated always as identity primary key, conversation_id uuid references mosuoe_conversations on delete cascade, sender text check(sender in ('student','mosuoe')), content text not null, created_at timestamptz default now());
create table public.subscriptions (id bigint generated always as identity primary key, student_id uuid references profiles, status text, product text, amount numeric, currency text default 'LSL', provider text, transaction_reference text, paid_at timestamptz);
create table public.notifications (id bigint generated always as identity primary key, user_id uuid references profiles on delete cascade, title text not null, body text, read_at timestamptz, created_at timestamptz default now());
alter table profiles enable row level security; alter table student_progress enable row level security; alter table mosuoe_conversations enable row level security; alter table mosuoe_messages enable row level security;
create policy "users read own profile" on profiles for select using (auth.uid()=id);
create policy "students read own progress" on student_progress for select using (auth.uid()=student_id);
create policy "students own conversations" on mosuoe_conversations for all using (auth.uid()=student_id);
create policy "conversation messages" on mosuoe_messages for all using (exists(select 1 from mosuoe_conversations c where c.id=conversation_id and c.student_id=auth.uid()));
